pool:
  vmImage: 'windows-latest'

variables:
  -template: playwright-variables.yml

trigger:
  branches:
    include:
      - 'main'

name: $(Build.BuildId)

stages:

  - stage: qa
    displayName: 'Run Automation Test - QA'
    dependsOn: []
    jobs:
      - template: playwright-template.yml
        parameters:
          BASE_URL: ${{ variables.DevURL }}