parameters:
  - name: BASE_URL
    type: string

steps:

  - download: none
  
  - checkout: self

  - task: NodeTool@0
    displayName: 'Use Node version 16'
    inputs:
      versionSpec: 16.x

  - script: |
      npm ci
    displayName: "NPM Install"

  - script: |
      npx playwright install --with-deps
    displayName: "Playwright Install"
    
  - script: |
      set BASE_URL=${{ parameters.BASE_URL }}
      set CI=true
      set PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml
      npx playwright test --workers=1
    displayName: "Run Playwright Tests"
    continueOnError: true
